dependencies:
  - name: elasticsearch
    version: 0.4.9
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: kibana
    version: 0.4.1
    repository: https://kubernetes-charts.storage.googleapis.com