dependencies:
  - name: elasticsearch
    version: 0.4.9
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
  - name: kibana
    version: 0.5.0
    repository: https://kubernetes-charts.storage.googleapis.com