dependencies:
  - name: elasticsearch
    version: 0.6.1
    repository: https://chartmuseum.build.cd.jenkins-x.io
  - name: kibana
    version: 0.5.0
    repository: https://kubernetes-charts.storage.googleapis.com